version: 0.2

env:
  variables:
    S3_BUCKET: 'beliciousbd'
    APP_NAME: 'foody-landing-page'
    BUILD_ENV: 'prod'

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g npm@6.12.1
      # Install Angular CLI
      - npm install -g @angular/cli@8.3.20
      # Install node dependancies.

  pre_build:
    commands:
      - echo Prebuild steps
      - npm install

  build:
    commands:
      # Builds Angular application. You can also build using custom environment here like mock or staging
      - echo Build started on `date`
      - ng build --${BUILD_ENV} --output-hashing=all

  post_build:
    commands:
      # Clear S3 bucket.
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo S3 bucket is cleared.
      # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
      - aws s3 cp dist/${APP_NAME} s3://${S3_BUCKET} --recursive
      - aws cloudfront create-invalidation --distribution-id=E2X5EKBPBRTUYH --paths="/*"
      - aws cloudfront create-invalidation --distribution-id=EC12JZXKHYJ0X --paths="/*"
      - echo Build completed on `date`
